apiVersion: v1
kind: Pod
metadata:
  name: flower-app-pod
  namespace: test-ns
spec:
  - containers:
    - name: test-container
      image: muralisocial123/flower-sample:v2.0
      ports:
        - containerPort: 3015